# Generated by Django 4.0.2 on 2022-02-18 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True
    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Codigo', models.IntegerField()),
                ('Nome', models.CharField(help_text='Informe o nome', max_length=100)),
                ('Email', models.CharField(help_text='Insira um e-mail', max_length=100)),
                ('Telefone', models.CharField(max_length=16)),
                ('Dtanas', models.DateField(help_text='Informe a data de nascimento')),
            ],
        ),
    ]
