# Generated by Django 4.0.2 on 2022-03-11 23:23
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compromisso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Codigo', models.IntegerField()),
                ('Data', models.DateField(help_text='Insira a data do rolê')),
                ('Hora', models.TimeField(help_text='Insira a hora do rolê')),
                ('Titulo', models.CharField(help_text='Insira o título do rolê', max_length=100)),
                ('Detalhes', models.CharField(help_text='Insira a descrição do rolê', max_length=150)),
            ],
        ),
    ]
